In [1]:
import numpy as np
import extract_features

C:\Users\Clarinet-VR\anaconda3\envs\keyNet_environment\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Clarinet-VR\anaconda3\envs\keyNet_environment\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Clarinet-VR\anaconda3\envs\keyNet_environment\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Clarine

In [3]:
feature_conf = extract_features.confs['hardnet']

extract_features.main(conf=feature_conf, list_images='test_im/image.txt')

Extract features for : KeyNet_HardNet

For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.



In [5]:
dsc = np.load('extracted_features/KeyNet_HardNet/test_im/test_im.ppm.dsc.npy')
kpt = np.load('extracted_features/KeyNet_HardNet/test_im/test_im.ppm.kpt.npy')

print("dsc.shape", dsc.shape)
print("kpt.shape", kpt.shape)

print("dsc", dsc)
print("kpt", kpt)

dsc.shape (1495, 128)
kpt.shape (1495, 4)
dsc [[ 0.02697773  0.09337678  0.08597216 ...  0.03389812 -0.04415694
   0.17677511]
 [ 0.02974526  0.10802355  0.06667711 ...  0.03455773 -0.05906097
   0.16001704]
 [-0.00655926  0.18335024  0.12550946 ...  0.0052624   0.04350467
   0.0840805 ]
 ...
 [-0.19153304  0.08488659  0.2116395  ...  0.09645231 -0.02772269
   0.09649689]
 [-0.01213393  0.08516002 -0.06265895 ... -0.01186793 -0.12841962
   0.05961721]
 [ 0.00326787 -0.08081295  0.02203921 ... -0.01544114  0.04671047
   0.01154539]]
kpt [[409.41482631 487.90367902   0.70710682 622.45336914]
 [409.         489.           1.00000006 607.70556641]
 [459.         488.           1.00000006 533.92730713]
 ...
 [359.91735162 173.94826817   0.70710682  15.91290665]
 [251.02290732 594.67680298   0.70710682  15.87627697]
 [367.69552622 387.49451609   0.70710682  15.85180569]]


In [2]:
feature_conf = extract_features.confs['sosnet']

extract_features.main(conf=feature_conf, list_images='test_im/image.txt')

conf {'name': 'SOSNet', 'pytorch_weight': 'SOSNet/sosnet-weights/sosnet-32x32-liberty.pth'}
Extract features for : KeyNet_SOSNet

For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.



In [3]:
dsc = np.load('extracted_features/KeyNet_SOSNet/test_im/test_im.ppm.dsc.npy')
kpt = np.load('extracted_features/KeyNet_SOSNet/test_im/test_im.ppm.kpt.npy')

print("dsc.shape", dsc.shape)
print("kpt.shape", kpt.shape)

print("dsc", dsc)
print("kpt", kpt)

dsc.shape (1495, 128)
kpt.shape (1495, 4)
dsc [[ 0.10265189 -0.12840281 -0.06470886 ...  0.13591132  0.01172903
   0.04633556]
 [ 0.08247709 -0.07058986 -0.06322752 ...  0.10042425  0.08039401
   0.05732325]
 [ 0.09547846 -0.03560368 -0.050007   ...  0.14626443  0.13748564
   0.0202977 ]
 ...
 [ 0.08249043 -0.10941934 -0.03898047 ...  0.0978486  -0.02580511
  -0.14865883]
 [ 0.06099408 -0.11915321 -0.03800565 ... -0.05173544  0.00778156
  -0.08280418]
 [ 0.12563814  0.13166732 -0.01713662 ...  0.10967847 -0.03434138
   0.1258879 ]]
kpt [[409.41482631 487.90367902   0.70710682 622.45336914]
 [409.         489.           1.00000006 607.70556641]
 [459.         488.           1.00000006 533.92730713]
 ...
 [359.91735162 173.94826817   0.70710682  15.91290665]
 [251.02290732 594.67680298   0.70710682  15.87627697]
 [367.69552622 387.49451609   0.70710682  15.85180569]]
