In [12]:
import sys, os
sys.path.append(os.path.join(os.getcwd(), "benchmark"))
sys.path.append(os.path.join(os.getcwd(), "benchmark_baselines"))
sys.path.append(os.path.join(os.getcwd(), "SOSNet"))
sys.path.append(os.path.join(os.getcwd(), "LoFTR"))
print(sys.path)

['/home/bankbiz/Documents/Key.Net', '/home/bankbiz/anaconda3/envs/keyNet_environment/lib/python37.zip', '/home/bankbiz/anaconda3/envs/keyNet_environment/lib/python3.7', '/home/bankbiz/anaconda3/envs/keyNet_environment/lib/python3.7/lib-dynload', '', '/home/bankbiz/anaconda3/envs/keyNet_environment/lib/python3.7/site-packages', '/home/bankbiz/anaconda3/envs/keyNet_environment/lib/python3.7/site-packages/IPython/extensions', '/home/bankbiz/.ipython', '/home/bankbiz/Documents/Key.Net/benchmark', '/home/bankbiz/Documents/Key.Net/benchmark_baselines', '/home/bankbiz/Documents/Key.Net/SOSNet', '/home/bankbiz/Documents/Key.Net/benchmark', '/home/bankbiz/Documents/Key.Net/benchmark_baselines', '/home/bankbiz/Documents/Key.Net/SOSNet', '/home/bankbiz/Documents/Key.Net/LoFTR']


In [16]:
import numpy as np
import cv2
import matplotlib.cm as cm

from matplotlib import pyplot as plt

In [ ]:
import extract_features

from benchmark import viz_stereo, config
from benchmark.methods.feature_matching import nn as match_features

In [ ]:
feature_conf = extract_features.confs['hardnet']
extract_features.main(conf=feature_conf, list_images='test_im/national_stadium.txt')

# dsc = np.load('extracted_features/KeyNet_HardNet/test_im/test_im.ppm.dsc.npy')
# kpt = np.load('extracted_features/KeyNet_HardNet/test_im/test_im.ppm.kpt.npy')

# print("dsc.shape", dsc.shape)
# print("kpt.shape", kpt.shape)

# print("dsc", dsc)
# print("kpt", kpt)

In [ ]:
feature_conf = extract_features.confs['sosnet']
extract_features.main(conf=feature_conf, list_images='test_im/national_stadium.txt')

In [17]:
dsc1 = np.load('extracted_features/KeyNet_SOSNet/test_im/IMG_1.1.jpg.dsc.npy')
dsc2 = np.load('extracted_features/KeyNet_SOSNet/test_im/IMG_1.2.jpg.dsc.npy')

kpt1 = np.load('extracted_features/KeyNet_SOSNet/test_im/IMG_1.1.jpg.kpt.npy')
kpt2 = np.load('extracted_features/KeyNet_SOSNet/test_im/IMG_1.2.jpg.kpt.npy')

print(dsc1.shape)
print(dsc2.shape)
print(kpt1)
print(kpt2.shape)

(1495, 128)
(1495, 128)
[[1.00000000e+02 7.00000000e+01 1.00000006e+00 7.41827454e+02]
 [1.01116270e+02 6.92964646e+01 7.07106823e-01 6.96965515e+02]
 [3.88908730e+02 3.47896536e+02 7.07106823e-01 5.54628479e+02]
 ...
 [2.82842712e+02 2.35466558e+02 7.07106823e-01 4.20580482e+01]
 [5.98212337e+02 2.54558441e+02 7.07106823e-01 4.19630928e+01]
 [5.02752921e+02 4.39113311e+02 7.07106823e-01 4.18444138e+01]]
(1495, 4)


In [ ]:
# cfg = config.get_config()
# match_features.match(dsc1, dsc2, cfg[0], kpt1, kpt2)